### ISSUE TITLE
Can't install GPE Plugin on a fresh Eclipse NEON installation

### ISSUE THREAD

**Issue by samgabriel** [gwt-plugins/gwt-eclipse-plugin#143]
When trying to install you always get the error. This is due to the dependency on the compatibility library which my understanding was that it was removed in Mars not sure how I was able to install it in my Mars installation before.

Software being installed: Google Plugin for Eclipse 4.4 0.0.0.201601131605 (com.google.gdt.eclipse.suite.e44.feature.feature.group 0.0.0.201601131605)
  Missing requirement: Google Plugin for Eclipse 4.4 0.0.0.201601131605 (com.google.gdt.eclipse.suite.e44.feature.feature.group 0.0.0.201601131605) requires 'org.eclipse.core.runtime.compatibility 0.0.0' but it could not be found

**Comment by michael-newsrx** [comment]
I'm trying to use either stable link or snapshot link and I get:

Cannot complete the install because one or more required items could not be found.
  Software being installed: Google Plugin for Eclipse 4.4 0.0.0.201601100516 (com.google.gdt.eclipse.suite.e44.feature.feature.group 0.0.0.201601100516)
  Missing requirement: Google Plugin for Eclipse 4.4 0.0.0.201601100516 (com.google.gdt.eclipse.suite.e44.feature.feature.group 0.0.0.201601100516) requires 'org.eclipse.core.runtime.compatibility 0.0.0' but it could not be found
