### ISSUE TITLE
Test on Eclipse Oxygen

### ISSUE THREAD

**Issue by branflake2267** [gwt-plugins/gwt-eclipse-plugin#299]

**Comment by TDesjardins** [comment]
Because of the upcoming release in june I tried to install the plugin with the last stable version eclipse 4.7M6 but the following error was thrown:

Cannot complete the install because one or more required items could not be found.
  Software being installed: GWT Eclipse Plugin 3.0.0.201703272136 (com.gwtplugins.eclipse.suite.v3.feature.feature.group 3.0.0.201703272136)
  Missing requirement: GWT Eclipse Plugin 3.0.0.201703272136 (com.gwtplugins.eclipse.suite.v3.feature.feature.group 3.0.0.201703272136) requires 'org.eclipse.mylyn.commons.ui 0.0.0' but it could not be found

The install of the SDBG plugin seems to work.

**Comment by TDesjardins** [comment]
Update: Installation of GWT Eclipse Plugin works after installing mylyn Plugin (http://download.eclipse.org/mylyn/releases/latest). After installation the plugin works as expected :-) .

**Comment by TDesjardins** [comment]
Plugin works perfectly fine with the new Eclipse Oxygen Release.

**Comment by okrasz** [comment]
It didn't want to work for me in Oxygen when installing via either via link drag&drop or via Marketplace when running Eclipse on Windows as without elevating to admin. It works after I started Eclipse as administrator and then installed via Marketplace, even if later not started as admin.

**Comment by branflake2267** [comment]
In progress...
