### ISSUE TITLE
It woud be better to change menu items order

### ISSUE THREAD

**Issue by slavap** [gwt-plugins/gwt-eclipse-plugin#311]
"GWT compile project" is used 99% of the time, so it would be better to remove or move to the end "New GWT application project" item.

![image](https://cloud.githubusercontent.com/assets/4129763/19706747/6c8e1824-9ac8-11e6-9b3b-5d10b74484f1.png)

Another options: different icons, default menu item is Compile, ...

**Comment by branflake2267** [comment]
I've been tempted to remove both because they have their default locations, such as project properties and the file new application flow. But since they have been around there from the beginning it's hard to remove them. And it's fun to have the icon on the top. 

Hm, you do have a point with how much it's used. Although from my angle it makes more sense to me to sort based on app lifecycle. 

I'd be interested in that type of sort if more speak up. If they were alpha sorted, it would sort to the top, which might be better too. :)

**Comment by slavap** [comment]
Please don't remove, I like and use this button all the time, icon on the top is really nice.

**Comment by branflake2267** [comment]
good point, I won't. I'm just speaking out loud what's gone through my thought process. :)

**Comment by branflake2267** [comment]
I've added a GWT Compiler launcher. The GWT Compiler can be added to favorites. 

At some point in the future the GWT Compile Project and GWT Compiler dialog will be switched to the launcher. I won't do this until things are stable. This will fix several issues, classpath issue, project focus issue, sorting issue. 

![screen shot 2016-10-31 at 5 42 05 am](https://cloud.githubusercontent.com/assets/1326504/19854587/feba6dde-9f2c-11e6-9fb3-d63a8cdd8b06.png)
![screen shot 2016-10-31 at 5 42 23 am](https://cloud.githubusercontent.com/assets/1326504/19854590/0193b1b4-9f2d-11e6-860b-eb6af1bc5b9b.png)
