### ISSUE TITLE
No repository found at http://storage.googleapis.com/gwt-eclipse-plugin/v3/release

### ISSUE THREAD

**Issue by rafacompu** [gwt-plugins/gwt-eclipse-plugin#396]
Repository at http://storage.googleapis.com/gwt-eclipse-plugin/v3/release does not response.

![image](https://user-images.githubusercontent.com/3905080/71480142-a8aa6000-27c5-11ea-9915-d1c3348bfe4d.png)

**Comment by optyfr** [comment]
They don't care apparently... furthermore this plugin does not work anymore with Eclipse 2020-09 because of method signature changes in jdt.internal.core

**Comment by niloc132** [comment]
This seems to be an invalid issue - the page isn't meant to be loaded by a browser, but by eclipse.  If you want to confirm that content is there, you can directly reference the html file (which google storage doesn't load automatically) as https://storage.googleapis.com/gwt-eclipse-plugin/v3/release/index.html and see the error popup that it creates, or https://storage.googleapis.com/gwt-eclipse-plugin/v3/release/p2.index to download part of the eclipse repo. Note that while I changed the urls to use https instead of http, they load just as easily with http.
