### ISSUE TITLE
HTTPS (discard http link)

### ISSUE THREAD

**Issue by Jos31fr** [gwt-plugins/gwt-eclipse-plugin#400]
Some jar files are downloaded from http url. Can you upgrade link to set up only https downloads?
http jar can be scanned and blocked by proxies

**Comment by niloc132** [comment]
This issue is moot - the eclipse marketplace has removed the old plugin since the previous maintainer refused to make this change. 

We now have a new marketplace entry, which is still pointing at the old plugin version for now, but is using https.

https://marketplace.eclipse.org/content/gwt-plugin
