### ISSUE TITLE
Annoying update notification

### ISSUE THREAD

**Issue by foal** [gwt-plugins/gwt-eclipse-plugin#97]
I have installed the GWT plugin "Google Plugin for Eclipse 4.4, 0.0.0.201509290133, com.google.gdt.eclipse.suite.e44.feature.feature.group, Google, Inc."

By the some reason I have BOTH update sites in eclipse preferences (it is a "bug" in another plugin):

Eclipse 4.4 GPE Repo	https://dl.google.com/eclipse/plugin/core/4.4	Enabled
and
repo	http://storage.googleapis.com/gwt-eclipse-plugin/release	Enabled
repo	http://storage.googleapis.com/gwt-eclipse-plugin/snapshot	Enabled

Because the both features have the same groupId Eclipse suggest to update to version 3.8.0 each 4 hours.

Not a big issue, but very annoying.

So may by change a version of plugin to 4.0.0 from 0.0.0?
or
change the groupId?

**Comment by branflake2267** [comment]
I don't want to change the 0.0.0 to a specific version because this would add some weight on maintenance of the project. There really should only be one update site per Eclipse install because of the conflicts. Since this is a fork it does carry some technical debt and one of the things I wanted to change but forgot to in the initial release was some of this. I think renaming the feature from Google plugin for Eclipse to GWT plugin and removing a version number would be of interest. In all the cases, since the workaround for this would be to have separate Eclipse installs for each plugin I rank this as a low priority at the moment. Ideally I would have done things a little differently but on the other hand there is a limited amount of time and many more issues that will go before this at the moment. Thanks for reporting none the less, I figured I share my thoughts on the subject.

**Comment by branflake2267** [comment]
Closing this because GPE-Fork is getting deprecated, and GWT Eclipse Plugin V3 is soon to take it's place.
